defaults:
  - optimizer: sgd_nnunet
  - scheduler: poly
  - loss: dice_ce
  - model: nnunet
  - dataset: segrap_unified
  - _self_

seed: 42
device: cuda

train:
  fold: 0
  num_folds: 5
  epochs: 1000
  batch_size: 2
  val_batch_size: 1
  test_batch_size: 1
  patch_size: [40, 196, 196]
  num_workers: 2
  num_iterations_per_epoch: 1
  num_val_iterations: 25
  oversample_foreground_percent: 0.33
  val_sliding_window: true
  val_overlap: 0.1
  use_amp: true
  deep_supervision: true
  save_every: 50
  output_dir: ./jm/result
